# SITE CONFIGURATION
title: My 日本語 studies
author: João Gabriel
description: > # Meta description of Homepage
  Um blog sobre meu progresso na aprendizado de japonês / A blog about my progress in learning japanese language.
baseurl: "/my-nihongo-studies"
url: "hhttps://jgobi.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: João Gabriel
  links:
    - https://twitter.com/jgabriel138
    - https://plus.google.com/+JoaoGabrielOliveira
    - https://github.com/jgobi

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}

tagline: >
  Um blog para escrever sobre meus avanços no estudo da lingua japonesa.

hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: jgobi@ufmg.br

twitter_username: jgabriel138 # replace with your_twitter_username or comment to remove link from footer
github_username:  jgobi # replace with your_github_username or comment to remove link from footer
# instagram_username: shanlongjj # replace with your_instagram_username or comment to remove link from footer

# disqus:
#   shortname: janczizikow # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
remote_theme: janczizikow/sleek
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
